name: Lobby
version: ${version.lobby}
main: pl.north93.zgame.lobby.Main
author: NorthPL93
depend: [API]

commands:
  lobbydevmode:
    description: "Włącza/Wyłącza dev mode na tym lobby."
    permission: "lobby.admin"